## SPDX-FileCopyrightText: 2016 Comcast Cable Communications Management, LLC
## SPDX-License-Identifier: Apache-2.0
# Default values for xmitd-talaria.

petasos:
  # docker image used
  image: xmidt/petasos
  address:
    host: ""
    port: "6400"

health:
  address:
    host: ""
    port: "6401"

pprof:
  address:
    host: ""
    port: "6402"

metric:
  address:
    host: ""
    port: "6403"  

# Pull secret used when images are stored in a private repository
# imagePullSecretName:


