---
# The unique fully-qualified-domain-name of the server.  It is provided to
# the X-petasos-Server header for showing what server fulfilled the request
# sent.
# (Optional)
server: (( grab $HOSTNAME || "petasos" ))

########################################
#   Labeling/Tracing via HTTP Headers Configuration
########################################

# Provides this build number to the X-petasos-Build header for
# showing machine version information.  The build number SHOULD
# match the scheme `version-build` but there is not a strict requirement.
# (Optional)
build: (( grab $BUILD || "unkown" ))

# Provides the region information to the X-petasos-Region header
# for showing what region this machine is located in.  The region
# is arbitrary and optional.
# (Optional)
region: "east"

# Provides the flavor information to the X-petasos-Flavor header
# for showing what flavor this machine is associated with.  The flavor
# is arbitrary and optional.
# (Optional)
flavor: (( grab $FLAVOR || "mint" ))

# stage is used for doing complex spruce manipulation
# change this will only effect spruce and the vars referencing it
stage: (( grab $STAGE || "dev" ))

##############################################################################
# WebPA Service configuration
##############################################################################

# For a complete view of the service config structure,
# checkout https://godoc.org/github.com/xmidt-org/webpa-common/server#WebPA

########################################
#   primary endpoint Configuration
########################################

# primary defines the details needed for the primary endpoint.  The
# primary endpoint accepts the events from petasos (typically).
# define https://godoc.org/github.com/xmidt-org/webpa-common/server#Basic
primary:
  # address provides the port number for the endpoint to bind to.
  # ":443" is ideal, but may require some special handling due to it being
  # a reserved (by the kernel) port.
  address: ":6400"
  # HTTPS/TLS
  #
  # certificateFile provides the public key and CA chain in PEM format if
  # TLS is used.  Note: the certificate needs to match the fqdn for clients
  # to accept without issue.
  #
  # keyFile provides the private key that matches the certificateFile
  # (Optional)
  # certificateFile: "/etc/petasos/public.pem"
  # keyFile: "/etc/petasos/private.pem"
########################################
#   health endpoint Configuration
########################################

# health defines the details needed for the health check endpoint.  The
# health check endpoint is generally used by services (like AWS Route53
# or consul) to determine if this particular machine is healthy or not.
# define https://godoc.org/github.com/xmidt-org/webpa-common/server#Health
health:
  # address provides the port number for the endpoint to bind to.
  # ":80" is ideal, but may require some special handling due to it being
  # a reserved (by the kernel) port.
  address: ":6401"

  # logInterval appears to be present from before we had formal metrics
  # (Deprecated)
  # logInterval: "60s"
  # options appears to be present from before we had formal metrics
  # (Deprecated)
  # options:
  #  - "PayloadsOverZero"
  #  - "PayloadsOverHundred"
  #  - "PayloadsOverThousand"
  #  - "PayloadsOverTenThousand"

########################################
#   Debugging/pprof Configuration
########################################

# pprof defines the details needed for the pprof debug endpoint.
# define https://godoc.org/github.com/xmidt-org/webpa-common/server#Basic
# (Optional)
pprof:
  # address provides the port number for the endpoint to bind to.
  address: ":6402"

########################################
#   Metrics Configuration
########################################

# metric defines the details needed for the prometheus metrics endpoint
# define https://godoc.org/github.com/xmidt-org/webpa-common/server#Metric
# (Optional)
metric:
  # address provides the port number for the endpoint to bind to.  Port 6404
  # was chosen because it does not conflict with any of the other prometheus
  # metrics or other machines in the xmidt cluster.  You may use any port you
  # wish.
  address: ":6403"

  # metricsOptions provides the details needed to configure the prometheus
  # metric data.  Metrics generally have the form:
  #
  # {namespace}_{subsystem}_{metric}
  #
  # so if you use the suggested value below, your metrics are prefixed like
  # this:
  #
  # xmidt_petasos_{metric}
  #
  # (Optional)
  metricsOptions:
    # namespace is the namespace of the metrics provided
    # (Optional)
    namespace: "xmidt"
    # subsystem is the subsystem of the metrics provided
    # (Optional)
    subsystem: "petasos"

########################################
#   Logging Related Configuration
########################################

# log configures the logging subsystem details
log:
  # file is the name of the most recent log file.  If set to "stdout" this
  # will log to os.Stdout.
  # (Optional) defaults to os.TempDir()
  # file: "/var/log/petasos/petasos.log"
  file: "stdout"

  # level is the logging level to use - INFO, DEBUG, WARN, ERROR
  # (Optional) defaults to ERROR
  level: "DEBUG"

  # maxsize is the maximum file size in MB
  # (Optional) defaults to max 100MB
  maxsize: 50

  # maxage is the maximum number of days to retain old log files
  # (Optional) defaults to ignore age limit (0)
  maxage: 30

  # maxbackups is the maximum number of old log files to retain
  # (Optional) defaults to retain all (0)
  maxbackups: 10

  # json is a flag indicating whether JSON logging output should be used.
  # (Optional) defaults to false
  json: true

########################################
#   Service Discovery Configuration
########################################

# service configures the server for service discovery.
# defined https://godoc.org/github.com/xmidt-org/webpa-common/service/servicecfg#Options
# this is required, consul or fixed must be used.
service:
  # defaultScheme, used for the registered servers for communication.
  # (Optional) defaults to https
  defaultScheme: http

  # vnodeCount used for consistent hash calculation github.com/billhathaway/consistentHash.
  # number of virtual nodes. should be a prime number
  # it is a tradeoff of memory and ~ log(N) speed versus how well the hash spreads
  # (Optional) defaults to 211
  vnodeCount: 211

  # disableFilter disables filtering.
  # (Deprecated) does not do anything
  # disableFilter: false

  # consul configures consul for service discovery.
  # defined https://godoc.org/github.com/xmidt-org/webpa-common/service/consul#Options
  # (Optional) defaults define https://sourcegraph.com/github.com/hashicorp/consul/-/blob/api/api.go#L347
  consul:
    # client is the configuration needed to connect to consul.
    # defined https://godoc.org/github.com/hashicorp/consul/api#Config
    client:
      # address is the address of the consul client or cluster.
      # (Optional) defaults to 127.0.0.1:8500
      address: (( grab $CONSUL_HOST || "consul:8500" ))

      # scheme is the scheme to use for api calls to the consul agent.
      # (Optional) defaults to http
      scheme: "http"

      # waitTime limits how long a Watch will block.
      # (Optional) defaults to 0s, aka wait forever before update
      waitTime: 30s

    # DisableGenerateID disables consul from generating the id.
    # (Optional) defaults to false
    disableGenerateID: true

    # DatacenterRetries is the number of attempts to get the datacenters
    # (Optional) defaults to 10
    datacenterRetries: 3

    # Registrations is a list of service(s) to register with consul.
    # defined https://godoc.org/github.com/hashicorp/consul/api#AgentServiceRegistration
    # (Optional) defaults to empty list
    registrations:
      - # id is the unique id for the service registration.
        id: (( grab server ))

        # name is the service name.
        name: "petasos"

        # tags are a list of strings that others talking to consul can use to
        # filter services.  These are meant to help in grouping similar
        # services in consul.
        # (Optional) defaults to empty list
        tags:
          - (( concat "stage=" stage))
          - (( concat "flavor=" flavor))

        # address tells consul where to contact the service.
        address: (( concat "http://" server ))

        # scheme tells consul what scheme to use to contact the service.
        # This is used with the address for calls to this server.
        scheme: "http"

        # port tells consul what port to use to contact the service.  This is
        # used with the address for calls to this server.
        port: 6400

        # checks is a list of checks to see if the service is healthy.
        # defined https://godoc.org/github.com/hashicorp/consul/api#AgentServiceCheck
        # (Optional) defaults to empty list
        # Warning: if there are no checks, this service will stay around even
        # when it is in a bad state.  This will cause other healthy servers
        # to send requests that will fail.
        checks:
          - # CheckID is a unique id for the check.
            checkID:  (( concat server ":http" ))

            # http tells consul to check via http rest request at the url
            # provided.
            http:  (( concat "http://" server ":6301/health" ))

            # interval is how often to check.
            interval: "30s"

            # deregisterCriticalServiceAfter is how long to wait before this
            # service is considered bad.
            deregisterCriticalServiceAfter: "70s"

    # Watches is a list of service(s) to watch from consul. The address of the
    # of the services are stored in memory. Upon update, the internal memory is
    # updated.
    # defined https://godoc.org/github.com/xmidt-org/webpa-common/service/consul#Watch
    # (Optional) defaults to empty list
    watches:
      - # service name to watch for updates.
        service: "talaria"

        # tags is a list of strings that must be attached to the services
        # being watched.
        # (Optional) defaults to empty list
        tags:
          - (( concat "stage=" stage))
          - (( concat "flavor=" flavor))

        # passingOnly determines if only services passing the consul check are returned.
        # (Optional) defaults to false
        passingOnly: true

        # allDatacenters determines if there is a watch for all datacenter changes.
        # change this to have the devices hash across all datacenters instead of
        # the single datacenter. The datacenter is known by the consul agent who is
        # aware of which datacenter it is in.
        # (Optional) defaults to false, aka only watch for services in the
        # current datacenter.
        allDatacenters: false

        # queryOptions are options for the consul query, used in conjunction
        # with passingOnly and allDatacenters.
        # defined by https://godoc.org/github.com/hashicorp/consul/api#QueryOptions
        # (Optional) defaults to empty struct
        # queryOptions:
        #   useCache: true
